### ISSUE TITLE
matched_ions outpuu

### ISSUE THREAD

**Issue by am-king** [dantheand/msms_structure_annot#9]
Currently organizes dataframe and generates excel output sorted by ion charge state. Would be better (for manual inspection) to sort first by a) hypothetical structure and then b) hypothetical MW (groups all charge states together).

Not terribly important, just listing things that would be more convenient.

**Comment by dantheand** [comment]
Changed the notebook sort

93c638a0f5d0bbda76224968cede393e0d8b894f
